import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  await prisma.action.deleteMany();
  await prisma.variable.deleteMany();
  await prisma.user.deleteMany();
  await prisma.roiSettings.deleteMany();

  // ── ROI Settings ────────────────────────────────────────────────────────
  await prisma.roiSettings.create({
    data: {
      currency: "EUR",
      discountRate: 0.08,
      taxRate: 0.3,
      cashflowHorizonYears: 10,
    },
  });

  // ── Users ───────────────────────────────────────────────────────────────
  const users = await Promise.all([
    prisma.user.create({ data: { name: "Lukas Holzinger", initials: "LH" } }),
    prisma.user.create({ data: { name: "Tom Kaercher", initials: "TK" } }),
    prisma.user.create({ data: { name: "Anna Mueller", initials: "AM" } }),
    prisma.user.create({ data: { name: "Sophie Bauer", initials: "SB" } }),
    prisma.user.create({ data: { name: "Max Weber", initials: "MW" } }),
    prisma.user.create({ data: { name: "Elena Fischer", initials: "EF" } }),
  ]);

  const [lukas, tom, anna, sophie, max, elena] = users;

  // ── Variables (price time-series) ───────────────────────────────────────
  const variables = await Promise.all([
    prisma.variable.create({
      data: {
        name: "Strompreis",
        description: "Durchschnittlicher Industriestrompreis Deutschland",
        unit: "EUR/kWh",
        method: "cagr",
        startYear: 2025,
        horizonYears: 10,
        startValue: 0.22,
        cagr: 0.03,
      },
    }),
    prisma.variable.create({
      data: {
        name: "CO2-Preis (EU ETS)",
        description: "EU Emissionshandelspreis pro Tonne CO2",
        unit: "EUR/t",
        method: "cagr",
        startYear: 2025,
        horizonYears: 10,
        startValue: 85,
        cagr: 0.07,
      },
    }),
    prisma.variable.create({
      data: {
        name: "Dieselpreis",
        description: "Durchschnittlicher Dieselpreis fuer Flottenfahrzeuge",
        unit: "EUR/l",
        method: "cagr",
        startYear: 2025,
        horizonYears: 10,
        startValue: 1.75,
        cagr: 0.04,
      },
    }),
    prisma.variable.create({
      data: {
        name: "Gaspreis",
        description: "Erdgaspreis Industrie Deutschland",
        unit: "EUR/kWh",
        method: "cagr",
        startYear: 2025,
        horizonYears: 10,
        startValue: 0.08,
        cagr: 0.05,
      },
    }),
    prisma.variable.create({
      data: {
        name: "Papierpreis",
        description: "Buero- und Kopierpapier A4 je Blatt",
        unit: "EUR/Blatt",
        method: "fix",
        startYear: 2025,
        horizonYears: 10,
        startValue: 0.015,
        cagr: 0,
      },
    }),
    prisma.variable.create({
      data: {
        name: "Abfallentsorgungskosten",
        description: "Gewerbliche Restmuellentsorgung pro Tonne",
        unit: "EUR/t",
        method: "cagr",
        startYear: 2025,
        horizonYears: 10,
        startValue: 180,
        cagr: 0.03,
      },
    }),
    prisma.variable.create({
      data: {
        name: "Wasserpreis",
        description: "Trink- und Abwasser Industrietarif",
        unit: "EUR/m3",
        method: "cagr",
        startYear: 2025,
        horizonYears: 10,
        startValue: 4.5,
        cagr: 0.02,
      },
    }),
    prisma.variable.create({
      data: {
        name: "Mindestlohn",
        description: "Gesetzlicher Mindestlohn Deutschland",
        unit: "EUR/h",
        method: "manual",
        startYear: 2025,
        horizonYears: 10,
        startValue: 12.82,
        cagr: 0,
        manualValues: JSON.stringify({
          2025: 12.82,
          2026: 13.5,
          2027: 14.0,
          2028: 14.5,
          2029: 15.0,
          2030: 15.5,
          2031: 16.0,
          2032: 16.5,
          2033: 17.0,
          2034: 17.5,
        }),
      },
    }),
  ]);

  const [strompreis, co2Preis, dieselpreis, _gaspreis, papierpreis, abfallpreis, _wasserpreis, _mindestlohn] = variables;

  // ── Actions with ROI data ───────────────────────────────────────────────
  await Promise.all([
    // ── OFFEN (5) ──────────────────────────────────────────────────
    prisma.action.create({
      data: {
        title: "Fuhrpark auf E-Fahrzeuge umstellen",
        description:
          "Schrittweise Ersetzung aller Diesel- und Benzin-Firmenwagen durch vollelektrische Fahrzeuge. Aufbau von Ladeinfrastruktur an den Standorten Muenchen und Hamburg.",
        status: "OFFEN",
        assigneeId: lukas.id,
        startDate: new Date("2025-10-01"),
        dueDate: new Date("2028-06-30"),
        createdAt: new Date("2025-07-08"),
        updatedAt: new Date("2025-07-08"),
        kpiName: "Dieselverbrauch Fuhrpark",
        kpiUnit: "Liter/Jahr",
        kpiBaselinePerYear: 45000,
        impactType: "reduction_percent",
        impactValue: 85,
        monetizationVariableId: dieselpreis.id,
        monetizationFixedEurPerUnit: null,
        capexEquipment: 320000,
        capexInstallation: 45000,
        capexSoftware: 0,
        capexConsulting: 8000,
        capexOther: 12000,
        grantAmount: 60000,
        grantPercent: null,
        opexMaintenance: 5000,
        opexLicenses: 0,
        opexPersonnel: 0,
        opexOther: 2000,
        otherBenefitsPerYear: 3000,
        otherCostsPerYear: 8000,
        depreciationYears: 8,
        justification: "THG-Reduktion Scope 1, Kostensenkung bei steigenden Dieselpreisen, BAFA-Foerderung E-Nutzfahrzeuge",
      },
    }),
    prisma.action.create({
      data: {
        title: "Mehrwegsystem in Bueros und Kantine einfuehren",
        description:
          "Abloesung aller Einwegbecher, -teller und -besteck durch ein Pfand-Mehrwegsystem. 500 Mehrwegbecher und Rueckgabestationen.",
        status: "OFFEN",
        assigneeId: anna.id,
        startDate: new Date("2025-09-01"),
        dueDate: new Date("2026-03-31"),
        createdAt: new Date("2025-06-15"),
        updatedAt: new Date("2025-06-15"),
        kpiName: "Einwegverpackungen",
        kpiUnit: "Stueck/Jahr",
        kpiBaselinePerYear: 60000,
        impactType: "reduction_percent",
        impactValue: 90,
        monetizationFixedEurPerUnit: 0.12,
        capexEquipment: 18000,
        capexInstallation: 3000,
        capexSoftware: 0,
        capexConsulting: 0,
        capexOther: 2000,
        grantAmount: 0,
        grantPercent: null,
        opexMaintenance: 2400,
        opexLicenses: 0,
        opexPersonnel: 4800,
        opexOther: 600,
        otherBenefitsPerYear: 500,
        otherCostsPerYear: 0,
        depreciationYears: 5,
        justification: "Plastiksteuer-Vermeidung, Mitarbeiter-Zufriedenheit, Abfallreduktion",
      },
    }),
    prisma.action.create({
      data: {
        title: "LED-Umruestung und Bewegungsmelder installieren",
        description:
          "Austausch saemtlicher Leuchtstoffroehren gegen LED-Panels. Installation von Bewegungsmeldern. Erwartete Energieeinsparung: ca. 35%.",
        status: "OFFEN",
        assigneeId: max.id,
        startDate: new Date("2025-08-01"),
        dueDate: new Date("2026-01-31"),
        createdAt: new Date("2025-05-20"),
        updatedAt: new Date("2025-05-20"),
        kpiName: "Stromverbrauch Beleuchtung",
        kpiUnit: "kWh/Jahr",
        kpiBaselinePerYear: 120000,
        impactType: "reduction_percent",
        impactValue: 35,
        monetizationVariableId: strompreis.id,
        capexEquipment: 42000,
        capexInstallation: 15000,
        capexSoftware: 0,
        capexConsulting: 0,
        capexOther: 3000,
        grantAmount: 0,
        grantPercent: null,
        opexMaintenance: 800,
        opexLicenses: 0,
        opexPersonnel: 0,
        opexOther: 0,
        otherBenefitsPerYear: 0,
        otherCostsPerYear: 0,
        depreciationYears: 10,
        justification: "BAFA-Energieaudit Empfehlung #1, schnelle Amortisation, CO2-Scope-2-Reduktion",
      },
    }),
    prisma.action.create({
      data: {
        title: "Digitale Dokumentenablage und E-Signatur einfuehren",
        description:
          "Migration aller papierbasierten Freigabeprozesse auf eine digitale Plattform. Ziel: 80% weniger Papierverbrauch.",
        status: "OFFEN",
        assigneeId: tom.id,
        startDate: new Date("2025-11-01"),
        dueDate: new Date("2026-04-30"),
        createdAt: new Date("2025-07-01"),
        updatedAt: new Date("2025-07-01"),
        kpiName: "Papierverbrauch",
        kpiUnit: "Blatt/Jahr",
        kpiBaselinePerYear: 500000,
        impactType: "reduction_percent",
        impactValue: 80,
        monetizationVariableId: papierpreis.id,
        capexEquipment: 0,
        capexInstallation: 0,
        capexSoftware: 24000,
        capexConsulting: 12000,
        capexOther: 0,
        grantAmount: 0,
        grantPercent: null,
        opexMaintenance: 0,
        opexLicenses: 9600,
        opexPersonnel: 0,
        opexOther: 0,
        otherBenefitsPerYear: 2000,
        otherCostsPerYear: 0,
        depreciationYears: 5,
        justification: "Prozesseffizienz, Papierreduktion, CSRD-Dokumentationspflicht",
      },
    }),
    prisma.action.create({
      data: {
        title: "Photovoltaikanlage auf Dach Werk Muenchen errichten",
        description:
          "120-kWp-Photovoltaikanlage auf der Produktionshalle. Eigenverbrauchsanteil: 60%.",
        status: "OFFEN",
        assigneeId: elena.id,
        startDate: new Date("2025-09-15"),
        dueDate: new Date("2026-06-30"),
        createdAt: new Date("2025-06-01"),
        updatedAt: new Date("2025-06-01"),
        kpiName: "Netzbezug Strom",
        kpiUnit: "kWh/Jahr",
        kpiBaselinePerYear: 180000,
        impactType: "reduction_absolute",
        impactValue: 72000,
        monetizationVariableId: strompreis.id,
        capexEquipment: 145000,
        capexInstallation: 25000,
        capexSoftware: 0,
        capexConsulting: 5000,
        capexOther: 8000,
        grantAmount: null,
        grantPercent: 15,
        opexMaintenance: 2500,
        opexLicenses: 0,
        opexPersonnel: 0,
        opexOther: 500,
        otherBenefitsPerYear: 4000,
        otherCostsPerYear: 1200,
        depreciationYears: 20,
        justification: "Scope-2-Reduktion, Stromkostensicherung, EEG-Einspeiseverguetung fuer Ueberschuss",
      },
    }),

    // ── IN_PROGRESS (4) ────────────────────────────────────────────
    prisma.action.create({
      data: {
        title: "Lieferanten-Audit nach ESG-Kriterien durchfuehren",
        description:
          "Systematische Bewertung der Top-40-Lieferanten anhand eines ESG-Scorecards.",
        status: "IN_PROGRESS",
        assigneeId: sophie.id,
        startDate: new Date("2025-03-01"),
        dueDate: new Date("2025-09-30"),
        createdAt: new Date("2025-01-10"),
        updatedAt: new Date("2025-06-20"),
        progressNote: "15 von 40 Lieferanten bewertet. 3 Vor-Ort-Audits durchgefuehrt.",
        kpiName: "Lieferanten mit ESG-Rating",
        kpiUnit: "Lieferanten/Jahr",
        kpiBaselinePerYear: 0,
        impactType: "reduction_absolute",
        impactValue: -40,
        monetizationFixedEurPerUnit: 2500,
        capexEquipment: 0,
        capexInstallation: 0,
        capexSoftware: 15000,
        capexConsulting: 35000,
        capexOther: 5000,
        grantAmount: 0,
        grantPercent: null,
        opexMaintenance: 0,
        opexLicenses: 6000,
        opexPersonnel: 24000,
        opexOther: 3000,
        otherBenefitsPerYear: 15000,
        otherCostsPerYear: 0,
        depreciationYears: 3,
        justification: "LkSG-Compliance, Lieferkettenresilienz, Reputationsrisiko-Minimierung",
      },
    }),
    prisma.action.create({
      data: {
        title: "Nachhaltigkeitsbericht 2024 nach GRI erstellen",
        description:
          "Erstellung des Nachhaltigkeitsberichts GJ 2024 nach GRI-Universal-Standards.",
        status: "IN_PROGRESS",
        assigneeId: tom.id,
        startDate: new Date("2025-04-01"),
        dueDate: new Date("2025-08-31"),
        createdAt: new Date("2025-03-15"),
        updatedAt: new Date("2025-07-01"),
        progressNote: "Datenerhebung zu 70% abgeschlossen. Erster Berichtsentwurf liegt vor.",
        kpiName: "GRI-Indikatoren abgedeckt",
        kpiUnit: "Indikatoren",
        kpiBaselinePerYear: 0,
        impactType: "reduction_absolute",
        impactValue: -35,
        monetizationFixedEurPerUnit: 500,
        capexEquipment: 0,
        capexInstallation: 0,
        capexSoftware: 8000,
        capexConsulting: 25000,
        capexOther: 0,
        grantAmount: 0,
        grantPercent: null,
        opexMaintenance: 0,
        opexLicenses: 4800,
        opexPersonnel: 18000,
        opexOther: 2000,
        otherBenefitsPerYear: 10000,
        otherCostsPerYear: 0,
        depreciationYears: 1,
        justification: "CSRD-Pflicht ab 2025, Investor Relations, Stakeholder-Transparenz",
      },
    }),
    prisma.action.create({
      data: {
        title: "Nachhaltigkeitsschulungen fuer alle Mitarbeitenden",
        description:
          "Modulares Schulungsprogramm (4 Pflichtmodule) fuer 280 Mitarbeitende ueber internes LMS.",
        status: "IN_PROGRESS",
        assigneeId: max.id,
        startDate: new Date("2025-05-01"),
        dueDate: new Date("2025-12-31"),
        createdAt: new Date("2025-04-01"),
        updatedAt: new Date("2025-06-15"),
        progressNote: "Schulungskonzept fertig. Pilotgruppe (32 Teilnehmer) hat Module 1-2 absolviert.",
        kpiName: "Geschulte Mitarbeitende",
        kpiUnit: "Personen",
        kpiBaselinePerYear: 0,
        impactType: "reduction_absolute",
        impactValue: -280,
        monetizationFixedEurPerUnit: 150,
        capexEquipment: 0,
        capexInstallation: 0,
        capexSoftware: 12000,
        capexConsulting: 18000,
        capexOther: 3000,
        grantAmount: 8000,
        grantPercent: null,
        opexMaintenance: 0,
        opexLicenses: 3600,
        opexPersonnel: 12000,
        opexOther: 1500,
        otherBenefitsPerYear: 5000,
        otherCostsPerYear: 0,
        depreciationYears: 3,
        justification: "CSRD-Anforderung, Mitarbeiterengagement, Fehlerreduktion durch Awareness",
      },
    }),
    prisma.action.create({
      data: {
        title: "Abfalltrennung und Recyclingquote verbessern",
        description:
          "5-Fraktionen-Trennstationen an allen Standorten. Ziel: 75% Recyclingquote.",
        status: "IN_PROGRESS",
        assigneeId: anna.id,
        startDate: new Date("2025-04-15"),
        dueDate: new Date("2025-10-31"),
        createdAt: new Date("2025-03-01"),
        updatedAt: new Date("2025-06-30"),
        progressNote: "Trennstationen Muenchen installiert. Hamburg folgt in KW 30.",
        kpiName: "Restmuellmenge",
        kpiUnit: "Tonnen/Jahr",
        kpiBaselinePerYear: 85,
        impactType: "reduction_percent",
        impactValue: 40,
        monetizationVariableId: abfallpreis.id,
        capexEquipment: 22000,
        capexInstallation: 5000,
        capexSoftware: 0,
        capexConsulting: 3000,
        capexOther: 2000,
        grantAmount: 0,
        grantPercent: null,
        opexMaintenance: 1500,
        opexLicenses: 0,
        opexPersonnel: 6000,
        opexOther: 800,
        otherBenefitsPerYear: 2000,
        otherCostsPerYear: 500,
        depreciationYears: 7,
        justification: "Kreislaufwirtschaftsgesetz, Entsorgungskostenreduktion, Scope-3-Reduktion",
      },
    }),

    // ── DONE (3) ───────────────────────────────────────────────────
    prisma.action.create({
      data: {
        title: "CO2-Bilanz Geschaeftsjahr 2024 berechnen und validieren",
        description:
          "Corporate Carbon Footprint GJ 2024 inkl. Scope 1-3. Externe Validierung durch TUeV Sued.",
        status: "DONE",
        assigneeId: elena.id,
        startDate: new Date("2025-01-15"),
        dueDate: new Date("2025-03-31"),
        createdAt: new Date("2025-01-10"),
        updatedAt: new Date("2025-03-28"),
        progressNote: "Bilanz fertiggestellt. Ergebnis: 1.240 t CO2e. Bericht uebergeben.",
        kpiName: "CO2-Emissionen Scope 1-3",
        kpiUnit: "t CO2e/Jahr",
        kpiBaselinePerYear: 1380,
        impactType: "reduction_absolute",
        impactValue: 140,
        monetizationVariableId: co2Preis.id,
        capexEquipment: 0,
        capexInstallation: 0,
        capexSoftware: 8000,
        capexConsulting: 22000,
        capexOther: 0,
        grantAmount: 0,
        grantPercent: null,
        opexMaintenance: 0,
        opexLicenses: 4000,
        opexPersonnel: 12000,
        opexOther: 0,
        otherBenefitsPerYear: 8000,
        otherCostsPerYear: 0,
        depreciationYears: 1,
        justification: "CSRD-Pflicht, Basis fuer Science-Based Targets, Investor-Anforderung",
      },
    }),
    prisma.action.create({
      data: {
        title: "Energieaudit nach DIN EN 16247 am Standort Muenchen",
        description:
          "Zertifiziertes Energieaudit: Gebaeudehuelle, Heizung, Druckluft, Beleuchtung, Produktion.",
        status: "DONE",
        assigneeId: lukas.id,
        startDate: new Date("2025-02-01"),
        dueDate: new Date("2025-04-30"),
        createdAt: new Date("2025-01-20"),
        updatedAt: new Date("2025-04-25"),
        progressNote: "Audit abgeschlossen. 12 Massnahmenvorschlaege. Top-3 in Umsetzungsplanung.",
        kpiName: "Energieverbrauch Gesamt",
        kpiUnit: "kWh/Jahr",
        kpiBaselinePerYear: 850000,
        impactType: "reduction_percent",
        impactValue: 12,
        monetizationVariableId: strompreis.id,
        capexEquipment: 0,
        capexInstallation: 0,
        capexSoftware: 0,
        capexConsulting: 18000,
        capexOther: 2000,
        grantAmount: 0,
        grantPercent: null,
        opexMaintenance: 0,
        opexLicenses: 0,
        opexPersonnel: 8000,
        opexOther: 0,
        otherBenefitsPerYear: 5000,
        otherCostsPerYear: 0,
        depreciationYears: 1,
        justification: "Gesetzliche Pflicht EDL-G, Basis fuer LED- und Druckluft-Massnahmen",
      },
    }),
    prisma.action.create({
      data: {
        title: "Verhaltenskodex fuer Lieferanten veroeffentlichen",
        description:
          "Supplier Code of Conduct: Menschenrechte, Umweltschutz, Anti-Korruption. Versand an 40 Lieferanten.",
        status: "DONE",
        assigneeId: sophie.id,
        startDate: new Date("2025-01-10"),
        dueDate: new Date("2025-05-31"),
        createdAt: new Date("2025-01-05"),
        updatedAt: new Date("2025-05-15"),
        progressNote: "Kodex finalisiert. 34 von 40 Lieferanten haben unterzeichnet.",
        kpiName: "Lieferanten mit CoC",
        kpiUnit: "Lieferanten",
        kpiBaselinePerYear: 0,
        impactType: "reduction_absolute",
        impactValue: -34,
        monetizationFixedEurPerUnit: 1000,
        capexEquipment: 0,
        capexInstallation: 0,
        capexSoftware: 0,
        capexConsulting: 15000,
        capexOther: 5000,
        grantAmount: 0,
        grantPercent: null,
        opexMaintenance: 0,
        opexLicenses: 0,
        opexPersonnel: 6000,
        opexOther: 2000,
        otherBenefitsPerYear: 8000,
        otherCostsPerYear: 0,
        depreciationYears: 3,
        justification: "LkSG-Compliance, Reputationsschutz, Voraussetzung fuer ESG-Lieferantenaudit",
      },
    }),
  ]);

  console.log("Seed completed: ROI settings, 6 users, 8 variables, 12 actions with ROI data.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
